# Generated by Django 5.2.5 on 2025-09-04 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bedequip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='patientdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=500)),
                ('phoneno', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='patients/')),
                ('place', models.CharField(max_length=600)),
                ('district', models.CharField(max_length=600)),
                ('state', models.CharField(max_length=600)),
                ('pin', models.IntegerField()),
                ('DIV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.division')),
            ],
        ),
        migrations.CreateModel(
            name='staffdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField()),
                ('name', models.CharField(max_length=600)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=500)),
                ('phoneno', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='staffs/')),
                ('USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('date', models.DateField()),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.staffdata')),
            ],
        ),
        migrations.CreateModel(
            name='medicinedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.staffdata')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.staffdata')),
            ],
        ),
    ]
