# Generated by Django 5.2.5 on 2025-09-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedata',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicinedata',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
