# Generated by Django 5.2.5 on 2025-09-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0003_alter_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedata',
            name='photo',
            field=models.ImageField(default=1, upload_to='medicines/'),
            preserve_default=False,
        ),
    ]
